export const DELETE_USER_TICKET = 'DELETE_USER_TICKET';
export const CLOSE_USER_TICKET = 'CLOSE_USER_TICKET';
export const OPEN_USER_TICKET = 'OPEN_USER_TICKET';
export const CREATE_USER_TICKET = 'CREATE_USER_TICKET';
